package com.syt.cellphone.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.syt.cellphone.pojo.PhoneRecommend;
import com.syt.cellphone.pojo.SearchHistory;
import com.syt.cellphone.pojo.PhoneBase;
import com.syt.cellphone.pojo.PhoneTrademark;
import com.syt.cellphone.pojo.Soc;

import com.syt.cellphone.greendao.PhoneRecommendDao;
import com.syt.cellphone.greendao.SearchHistoryDao;
import com.syt.cellphone.greendao.PhoneBaseDao;
import com.syt.cellphone.greendao.PhoneTrademarkDao;
import com.syt.cellphone.greendao.SocDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneRecommendDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig phoneBaseDaoConfig;
    private final DaoConfig phoneTrademarkDaoConfig;
    private final DaoConfig socDaoConfig;

    private final PhoneRecommendDao phoneRecommendDao;
    private final SearchHistoryDao searchHistoryDao;
    private final PhoneBaseDao phoneBaseDao;
    private final PhoneTrademarkDao phoneTrademarkDao;
    private final SocDao socDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneRecommendDaoConfig = daoConfigMap.get(PhoneRecommendDao.class).clone();
        phoneRecommendDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        phoneBaseDaoConfig = daoConfigMap.get(PhoneBaseDao.class).clone();
        phoneBaseDaoConfig.initIdentityScope(type);

        phoneTrademarkDaoConfig = daoConfigMap.get(PhoneTrademarkDao.class).clone();
        phoneTrademarkDaoConfig.initIdentityScope(type);

        socDaoConfig = daoConfigMap.get(SocDao.class).clone();
        socDaoConfig.initIdentityScope(type);

        phoneRecommendDao = new PhoneRecommendDao(phoneRecommendDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        phoneBaseDao = new PhoneBaseDao(phoneBaseDaoConfig, this);
        phoneTrademarkDao = new PhoneTrademarkDao(phoneTrademarkDaoConfig, this);
        socDao = new SocDao(socDaoConfig, this);

        registerDao(PhoneRecommend.class, phoneRecommendDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(PhoneBase.class, phoneBaseDao);
        registerDao(PhoneTrademark.class, phoneTrademarkDao);
        registerDao(Soc.class, socDao);
    }
    
    public void clear() {
        phoneRecommendDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        phoneBaseDaoConfig.clearIdentityScope();
        phoneTrademarkDaoConfig.clearIdentityScope();
        socDaoConfig.clearIdentityScope();
    }

    public PhoneRecommendDao getPhoneRecommendDao() {
        return phoneRecommendDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public PhoneBaseDao getPhoneBaseDao() {
        return phoneBaseDao;
    }

    public PhoneTrademarkDao getPhoneTrademarkDao() {
        return phoneTrademarkDao;
    }

    public SocDao getSocDao() {
        return socDao;
    }

}
