package com.syt.cellphone.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.syt.cellphone.pojo.PhoneRecommend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PHONE_RECOMMEND".
*/
public class PhoneRecommendDao extends AbstractDao<PhoneRecommend, Integer> {

    public static final String TABLENAME = "PHONE_RECOMMEND";

    /**
     * Properties of entity PhoneRecommend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property RecommendId = new Property(0, int.class, "recommendId", true, "RECOMMEND_ID");
        public final static Property PhoneId = new Property(1, int.class, "phoneId", false, "PHONE_ID");
        public final static Property RecommendReimage = new Property(2, String.class, "recommendReimage", false, "RECOMMEND_REIMAGE");
    }


    public PhoneRecommendDao(DaoConfig config) {
        super(config);
    }
    
    public PhoneRecommendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PHONE_RECOMMEND\" (" + //
                "\"RECOMMEND_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: recommendId
                "\"PHONE_ID\" INTEGER NOT NULL ," + // 1: phoneId
                "\"RECOMMEND_REIMAGE\" TEXT);"); // 2: recommendReimage
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PHONE_RECOMMEND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PhoneRecommend entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getRecommendId());
        stmt.bindLong(2, entity.getPhoneId());
 
        String recommendReimage = entity.getRecommendReimage();
        if (recommendReimage != null) {
            stmt.bindString(3, recommendReimage);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PhoneRecommend entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getRecommendId());
        stmt.bindLong(2, entity.getPhoneId());
 
        String recommendReimage = entity.getRecommendReimage();
        if (recommendReimage != null) {
            stmt.bindString(3, recommendReimage);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public PhoneRecommend readEntity(Cursor cursor, int offset) {
        PhoneRecommend entity = new PhoneRecommend( //
            cursor.getInt(offset + 0), // recommendId
            cursor.getInt(offset + 1), // phoneId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // recommendReimage
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PhoneRecommend entity, int offset) {
        entity.setRecommendId(cursor.getInt(offset + 0));
        entity.setPhoneId(cursor.getInt(offset + 1));
        entity.setRecommendReimage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(PhoneRecommend entity, long rowId) {
        return entity.getRecommendId();
    }
    
    @Override
    public Integer getKey(PhoneRecommend entity) {
        if(entity != null) {
            return entity.getRecommendId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PhoneRecommend entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
